language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
# install dependencies
install: "pip install -r dev-requirements.txt"
# run tests
script: nosetests
after_sucess:
    - coveralls
